version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_bot_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/app
